config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'

  # root 'users#index'

  resources :bookings
  resources :reservations
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord

    belongs_to :user, optional: true
	validates :reserve_name, presence: true
	# validates :reserve_date, presence: true
	validates :room_type, presence: true, inclusion: { in: ['single', 'double', 'twin'] }
	validates :plan, presence: true, inclusion: { in: ['economy', 'normal', 'special'] }
	attribute :start_time, :datetime
	validate :start_time_uniqueness_by_date
	validate :date_before_start

	def start_time_uniqueness_by_date
 	 	if Booking.exists?(start_time: start_time.beginning_of_day..start_time.end_of_day)
			errors.add(:base, "#{start_time.to_date} は他のユーザーが予約しています")
	  	end
	end

	def date_before_start
		errors.add(:base, '過去の日付は選択できません') if start_time < Date.today
	end

	# validates :start_time, uniqueness: { message: 'は他のユーザーが予約しています' }
	# validates :date_before_start

	# def date_before_start
	# 	errors.add(:start_time, "は過去の日付を選択できません")if start_time < Date.today
	# end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :bookings, dependent: :destroy

  validates :loginname, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true
  validates :password_digest, presence: false
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:error] = "Login required."
      redirect_to login_path
    end
  end

  def logged_in?
    session[:user_id].present?
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :require_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    # @bookings = Booking.order(reserve_date: :asc)
    @bookings = Booking.all 
	@users = User.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:start_time, :title, :reserve_name, :reserve_date, :room_type, :plan, :user_id)
    end

    def require_booking
      @booking = Booking.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]
  
  def new
  
  end

  def create
    loginname = params[:loginname]
    password = params[:password]

    user = User.find_by(loginname: params[:loginname])

    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to bookings_url, notice: "You have been successfully logged in."
    else
      redirect_to login_url, alert: "Invalid loginname or password."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to bookings_url, notice: "You have been successfully logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: [:index, :show, :new, :create]


  # GET /users or /users.json
  def index
    @users = User.all
	@bookings = Booking.order(reserve_date: :asc)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:loginname, :name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">

<br><br>
  <p>
    <strong>Name:</strong>
    <%= booking.reserve_name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%# <%= booking.reserve_date %>
    <%= booking.start_time %>
  </p>
  
  <p>
    <strong>Room:</strong>
    <%= booking.room_type %>
  </p>
  
  <p>
    <strong>Plan:</strong>
    <%= booking.plan %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
  	

  <div>
    <%= form.label :reserve_name, style: "display: block" %>
    <%= form.text_field :reserve_name, value: User.find(session[:user_id]).loginname, class: 'c-form-text' %>
  </div><br>
  
  
  

  <div class="time">
    <%= form.label :reserve_date, style: "display: block" %>
    <%= form.datetime_select :start_time %>
  </div><br>

  <%# <div> %>
    <%# <%= form.label :reserve_date, style: "display: block" %>
    <%# <%= form.date_field :reserve_date, class: 'c-form-text-2' %> 
  <%# </div><br> %> 
  
  
 
  
  
  <div>
    <%= form.label :room_type, style: "display: block" %>
	<%= form.select :room_type, ['single', 'twin', 'double'], {include_blank: '選択してください'}, class: 'c-form-text-2' %>
  </div><br>
  

  <div class="plan">
    <%= form.label :plan, style: "display: block" %>
    <%= form.select :plan, ['economy', 'normal', 'special'], {include_blank: '選択してください'}, class: 'c-form-text-2' %>
  </div><br><br>


  <div>
	<%= form.submit "Create booking", class: "btn_02" %>
  </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<p><%= link_to "Top", bookings_path %>　/　<%= link_to "Mypage", users_path %>　/　<%= link_to "Booking_datail", @booking %>　/　edit</p>
<div class = "new">

<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>


</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>


<h1 class = "toppage_h1">　Introduce</h1>

<div class = "introduce">
	<img src="/assets/hotel.png" alt="" class = "hotelimg">
	<ul class = "introduce_ul">
		<li>オープン日 : 2023/5/1</li>
		<li>サーバー名 : Kaoeri.aternos.me</li>
		<li>住所 : ウミベ</li>
		<li>座標 : x110 y11 z60</li>
		<li>気候 : 草原</li>
		<br><br>
		<div class = "new_booking_button">
			<%= link_to ">　Go to mypage", users_path %>
		</div>
	</ul>
</div>



<br><br><br>
<h1 class = "toppage_h1">　Room Type</h1>
<div class = "introduce">
	<div class="room">
        <div class="room_tape"> </div>
        <p class="room_title">Single</p>
        <img src="/assets/single.png" alt="" class = "room_img">
		<span class="description_bottom">
			<ul>
				<li>シティビュー</li>
				<li>チェスト1個</li>
			</ul>
		</span>
    </div>
	
	<div class="room">
        <div class="room_tape"> </div>
        <p class="room_title">Twin</p>
        <img src="/assets/twin.png" alt="" class = "room_img">
		<span class="description_bottom">
			<ul>
				<li>オーシャンビュー</li>
				<li>チェスト2個</li>
			</ul>
		</span>
    </div>
	
	<div class="room">
        <div class="room_tape"> </div>
        <p class="room_title">Double</p>
        <img src="/assets/double.png" alt="" class = "room_img">
		<span class="description_bottom">
			<ul>
				<li>オーシャンビュー</li>
				<li>チェスト2個</li>
			</ul>
		</span>
    </div>
</div>





<br><br><br>
<h1 class = "toppage_h1">　Plan</h1>
<ul>
		<li>economy : 素泊まり</li>
		<li>normal : 朝食付き</li>
		<li>special : 朝食・夕食付き</li>
</ul>




<br><br><br>
<h1 class = "toppage_h1">　Latest booking</h1>
<div id="bookings">
  
  <%= month_calendar events: @bookings do |date, bookings| %>
  <%= date.day %>

    <% bookings.each do |booking|%>
    
	<% if((User.find(session[:user_id]).loginname) ==  booking.reserve_name )%>
      <div class = "your">
        <%= booking.reserve_name %> (<%= booking.room_type %>)
      </div>
	  
	<% else %>
		<div>
			<%= booking.reserve_name %> (<%= booking.room_type %>)
		</div>	
    <% end %> 
	<% end %>
  <% end %>
    

</div>
</div>

app/views/bookings/new.html.erb
<p><%= link_to "Top", bookings_path %>　/　<%= link_to "Mypage", users_path %>　/　New_booking</p>

<div class = "new">
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<p><%= link_to "Top", bookings_path %>　/　<%= link_to "Mypage", users_path %>　/　Booking_datail</p>
<%= render @booking %>

<div>
  <%= link_to ">　Edit this booking", edit_booking_path(@booking) %>
	<br><br>
	<%= button_to "Delete this booking", @booking, { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } }, method: :get, class: "btn_03"} %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <header>
        <div class = "title"><h1>Booking hotel</h1></div>
        <nav class = "item">
		
		
            <% if session[:user_id]%>
		<p> <%= User.find(session[:user_id]).loginname %>さんようこそ </p>
		<%= button_to "Logout", logout_path, method: :delete, class: "btn_04" %>
		
		<% end %>
        </nav>
    </header>

  
  <body>
  <div class = "flex-container">
    
    <%= yield %>
  </div>
  </body>
  
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :reserve_name, style: "display: block" %>
    <%= form.date_field :reserve_name %>
  </div>

  <div>
    <%= form.label :reserve_date, style: "display: block" %>
    <%= form.date_field :reserve_date %>
  </div>

  <div>
    <%= form.label :room_type, style: "display: block" %>
    <%= form.text_field :room_type %>
  </div>

  <div>
    <%= form.label :plan, style: "display: block" %>
    <%= form.text_field :plan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>Reserve date:</strong>
    <%= reservation.reserve_date %>
  </p>

  <p>
    <strong>Room type:</strong>
    <%= reservation.room_type %>
  </p>

  <p>
    <strong>Plan:</strong>
    <%= reservation.plan %>
  </p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <p>
      <%= link_to "Show this reservation", reservation %>
    </p>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "contens">
  <div>
    <%= form.label :loginname, style: "display: block" %>
    <%= form.text_field :loginname, class: 'c-form-text-2', autocomplete: "off" %>
  </div><br>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'c-form-text-2', autocomplete: "off" %>
  </div><br>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: 'c-form-text-2', autocomplete: "off" %>
  </div><br>


  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, class: 'c-form-text-2' %>
  </div><br>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation, class: 'c-form-text-2' %>
  </div><br><br>

  <div>
	<%= form.submit "Create user", class: "btn_02" %>
  </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<br><br>
  <div>
  <p>
    <strong>Loginname:</strong>
    <%= user.loginname %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
  
  
  
  </div>

</div>

app/views/users/edit.html.erb
<p><%= link_to "Top", bookings_path %>　/　<%= link_to "Mypage", users_path %>　/　<%= link_to "User_datail", @user %>　/　edit</p>
<div class = "new">
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>


</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<div class = "mypage">
<p><%= link_to "Top", bookings_path %>　/　Mypage</p>
</div>

<div class = "new_booking_button">
			<%= link_to ">　New booking", new_booking_path %>
</div>

<h1 class = "toppage_h1">　Your booking</h1>
<table class = "booking_list">
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Room</th>
      <th>Plan</th>
    </tr>
  </thead>
  <tbody>
  
    <% @bookings.each do |booking| %>
	<% if((User.find(session[:user_id]).loginname) ==  booking.reserve_name )%>
      <tr>
        <td><%= booking.start_time %></td>
        <td><%= booking.reserve_name %></td>
        <td><%= booking.room_type %></td>
        <td><%= booking.plan %></td>
		<td><%= link_to "> detail", booking %></td>
		
      </tr>
	 <% end %>
    <% end %>
  </tbody>
</table>	

<br><br>
<h1 class = "toppage_h1">　Your information</h1>

  <% @users.each do |user| %>
  <div class = "user_information">
	<% if((User.find(session[:user_id]).loginname) ==  user.loginname )%>
    <p>
		<strong>Loginname:</strong>
		<%= user.loginname %>
	</p>

	<p>
		<strong>Name:</strong>
		<%= user.name %>
	</p>

	<p>
		<strong>Email:</strong>
		<%= user.email %>
	</p>
	
	
	
	<p>
		<strong>Password:</strong>
		<%= "****" %>
	</p>
	<%= link_to "> detail", user %>
	</div>
	<% end %>
   <% end %>
	
	
</div>

app/views/users/new.html.erb
<div class = "new">
<h1>New user</h1>

<%= render "form", user: @user %>

<br>


  <%= link_to "<　Back to Login page", login_path %>

</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<p><%= link_to "Top", bookings_path %>　/　<%= link_to "Mypage", users_path %>　/　User_datail</p>
<%= render @user %>

<div>
  <%= link_to ">　Edit this user", edit_user_path(@user) %>
	<br><br>
  <%= button_to "Delete this user", @user, { method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } }, method: :get, class: "btn_03" } %>
</div>